from flask import Flask, request, jsonify
from db import create_connection
from order_processing import generate_barcode_image
import uuid

app = Flask(__name__)

@app.route('/submit_order', methods=['POST'])
def submit_order():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Missing JSON data"}), 400

    # Extract required fields from JSON data
    customer_name = data.get('customer_name')
    product_id = data.get('product_id')
    quantity = data.get('quantity')

    if not all([customer_name, product_id, quantity]):
        return jsonify({"error": "Missing fields"}), 400

    # Generate a unique order ID for the order
    # In a real application, this would be generated by the database
    order_id = str(uuid.uuid4())

    # TODO: Save order to DB here using order_id...

    # Generate barcode image as base64 string
    barcode_base64 = generate_barcode_image(order_id)

    return jsonify({
        "message": "Order submitted!",
        "order_id": order_id,
        "barcode_base64": barcode_base64
    }), 200

if __name__ == '__main__':
    print("Registered routes:")
    print(app.url_map)
    app.run(debug=True)
